apiVersion: apps.nginxweb.io/v1
kind: Application
metadata:
  name: nginx-web-application
  namespace: nginx-web
spec:
  project: default
  source:
    repoURL: https://github.com/efi-pasaar/learning-with-argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-web
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
